global using Bogus;
global using PetAdopt.Domain.Aggregates.NgoAggregate;
global using PetAdopt.Domain.ValueObjects;
global using PetAdopt.UnitTests.GeneratorBogus;
global using PetAdopt.Domain.AggregatesModels.AdoptionFormAggregate;
global using PetAdopt.UnitTests.GeneratorBogus.PetAggregate;
global using PetAdopt.Domain.AggregatesModels.AdoptionAggregate;
global using PetAdopt.Domain.Enums;
global using PetAdopt.Domain.AggregatesModels.PetAggregate;