services:
  petadopt.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionString=Server=petadopt.database,1433;Database=PetAdopt;User Id=sa;Password=12345!#Admin;TrustServerCertificate=True;Trusted_Connection=false;
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PATH_BASE=/petadopt.api
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - petadopt.database
      - zookeeper
    networks:
      - my-network

  petadopt.database:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=12345!#Admin
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - my-network

  zookeeper:
    image: zookeeper:3.9.0
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181  
      - ZOOKEEPER_TICK_TIME=2000  
      - ZOOKEEPER_MAX_BUFFER=10485760 
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
    - "9092:9092"  
    - "9093:9093"  
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_MESSAGE_MAX_BYTES: 200000000 
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000 
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9998
      KAFKA_JMX_OPTS: '-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999'
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - my-network

  kafka-manager:
    image: hlebalbau/kafka-manager:2.0.0.2
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_BROKER_CONNECT: kafka:9092
    depends_on:
      - zookeeper
      - kafka
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
  kafka-data:

