services:
  petadopt.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      # - ConnectionString=${Server=193.167.200.89;Database=;User Id=321;Password=321;TrustServerCertificate=True;Trusted_Connection=false;}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PATH_BASE=/petadopt.api
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  petadopt.database:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=12345!#Admin
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
